In [0]:
import numpy as np

array=np.array([[1,2,3],[2,3,4]],dtype=np.int32)
a=np.zeros((3,4))
ab=np.ones((3,4))


print(array)
print(array.dtype)
print('dimension',array.ndim)
print('shape',array.shape)
print('size',array.size)
print(a)
print(ab)

[[1 2 3]
 [2 3 4]]
int32
dimension 2
shape (2, 3)
size 6
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [0]:
aa=np.arange(12)
ac=np.arange(12).reshape((3,4))
ad=np.linspace(1,10,4).reshape((2,2))

print(ac)
print(ad)
print(ad<3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1.  4.]
 [ 7. 10.]]
[[ True False]
 [False False]]


In [0]:
aaa=np.array([[1,1],[0,1]])
bbb=np.arange(4).reshape((2,2))
#矩阵乘法 
ccc=np.dot(aaa,bbb)
c_dot=aaa.dot(bbb)

print(ccc)
print(c_dot)

[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [0]:
aab=np.random.random((2,4))

print(aab)
print(np.sum(aab,axis=1))
#axis=1，列数求和
#axis=0，行数求和
print(np.min(aab,axis=0))
print(np.max(aab))

[[0.62266373 0.87322237 0.15608466 0.97606995]
 [0.53131739 0.84275723 0.67052047 0.61273152]]
[2.6280407  2.65732662]
[0.53131739 0.84275723 0.15608466 0.61273152]
0.9760699465973214
